version: "1"
services:
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: admin
        ports:
            - 5432:5432
        volumes:
            - ./db-scripts/create-securities-table.sql:/docker-entrypoint-initdb.d/create-securities-table.sql
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    fastapi:
        build: ./fastapi
        environment:
            host_server: db
            db_server_port: 5432
            database_name: postgres
            db_username: postgres
            db_password: admin
        ports:
            - 8081:80
        depends_on: 
            - db
    